// user login/logout
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"

// user registration/signup
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

// All products  
export const ALL_PRODUCTS_REQUEST = "ALL_PRODUCTS_REQUEST"
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS"
export const ALL_PRODUCTS_FAIL = "ALL_PRODUCTS_FAIL"

// home products(featured categories, featured products, popular products recently viewed)
export const PRODUCTS_INDEX_REQUEST = "PRODUCTS_INDEX_REQUEST"
export const PRODUCTS_INDEX_SUCCESS = "PRODUCTS_INDEX_SUCCESS"
export const PRODUCTS_INDEX_FAIL = "PRODUCTS_INDEX_FAIL"

// Search
export const SEARCH_PRODUCTS_REQUEST = "SEARCH_PRODUCTS_REQUEST"
export const SEARCH_PRODUCTS_SUCCESS = "SEARCH_PRODUCTS_SUCCESS"
export const SEARCH_PRODUCTS_FAIL = "SEARCH_PRODUCTS_FAIL"

// category list
export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST"
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS"
export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL"

// category detail
export const CATEGORY_DETAIL_REQUEST = "CATEGORY_DETAIL_REQUEST"
export const CATEGORY_DETAIL_SUCCESS = "CATEGORY_DETAIL_SUCCESS"
export const CATEGORY_DETAIL_FAIL = "CATEGORY_DETAIL_FAIL"

// product detail
export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST"
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS"
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL"

// product review
export const PRODUCT_REVIEW_REQUEST = "PRODUCT_REVIEW_REQUEST"
export const PRODUCT_REVIEW_SUCCESS = "PRODUCT_REVIEW_SUCCESS"
export const PRODUCT_REVIEW_FAIL = "PRODUCT_REVIEW_FAIL"
