# Generated by Django 5.1 on 2024-08-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='email', max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='username', max_length=255, unique=True, verbose_name='Username'),
        ),
    ]
